server:
  port: 8080
  error:
    include-stacktrace: never

spring:
  datasource:
    url: jdbc:h2:mem:coins_db
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: validate
  h2.console.enabled: true
  liquibase:
    changeLog: classpath:/db/changelog/db.changelog-root.xml
    url: jdbc:h2:mem:coins_db
    user: sa
    password: sa

frontEnd:
  url: http://localhost:4200

swagger:
  permittedMatchers: >
    /v3/api-docs/**,
    /swagger-ui/**,
    /swagger-resources,
    /swagger-resources/**,
    /swagger-ui.html/**,
    /webjars/**

security:
  permittedMatchers: >
    /h2-console/**,
    /users/login,
    /error,
    /users/login


user:
  employees:
    roles: ADMIN,EMPLOYEE
  client:
    roles: USER,SENDER,RECEIVER
  default:
    password: ${CD_USER_DEFAULT_PASSWORD}

  profile:
    image-url: "http://localhost:${server.port}/users/image?name="
    dir: "${user.home}/coin-code/images/user-profiles"

coin:
  image:
    dir: "${user.home}/coin-code/images/coins"