server:
  port: 8080
  error:
    include-stacktrace: never

spring:
  datasource:
    url: jdbc:h2:mem:coins_db
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: validate
  h2.console.enabled: true
  liquibase:
    changeLog: classpath:/db/changelog/db.changelog-root.xml
    url: jdbc:h2:mem:coins_db
    user: sa
    password: sa

frontEnd:
  url: http://localhost:4200

security.permittedMatchers: >
  /h2-console/**,
  /users/login,
  /error

user:
  default:
    roles: USER,SENDER,RECEIVER
    password: ${CD_USER_DEFAULT_PASSWORD}

  profile:
    image-url: "http://localhost:${server.port}/users/image?name="
    dir: "${user.home}/coin-code/images/user-profiles"
