spring:
  datasource:
    url: jdbc:h2:mem:coins_db
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2.console.enabled: true
  liquibase:
    changeLog: classpath:/db/changelog/db.changelog-root.xml
    url: jdbc:h2:mem:coins_db
    user: sa
    password: sa

frontEnd:
  url: http://localhost:4200
